### ISSUE TITLE
add copyable ready to go R code option to paste into shiny app?

### ISSUE THREAD

**Issue by AdamSpannbauer** [AlexanderHolmes0/Meta_Creator#1]
I think it'd be nice to have an option of a more shiny ready tags to paste in (assuming shiny users are main target).

I'd envision this as an option (maybe radio buttons) of R shiny vs plain HTML.  If R is selected then the same tags shown can appear, but wrapped in quotes and the shiny `HTML()` function.  I think this would be a pretty low cost add and save a little headache for newer shiny people that want to spruce up their app but don't have familiarity with the `HTML()` function already.  

An additional nice add to pork barrel on to this might be a 'copy' button that automagically puts the code on the user's clipboard

**Comment by AlexanderHolmes0** [comment]
Love the ideas. It is done/published 💯
